---
title: RESTHeart
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: docs
  values:
    old_docs: false
- scope:
    path: docs/v3
  values:
    old_docs: true
encoding: utf-8
email: info@softinstigate.com
description: The leading REST API Server for MongoDB.
baseurl: ''
url: https://restheart.org
twitter_username: softinstigate
github_username: softinstigate
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
highlighter: rouge
paginate: 7
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
excerpt_separator: "<!-- more -->"
sass:
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
domain: restheart.org
google_analytics_tracking_id: UA-49060386-2
hotjar_analytics: true
cookie_banner: true
blog:
  tags:
    url: "/blog/tags/"
    title_prefix: 'blog - tag: '
    layout: tag.html
  categories:
    url: "/blog/categories/"
    title_prefix: 'blog - category: '
    layout: category.html
